name: build

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "src/**"
      - "xmake.lua"
      - "xmake-packages/**"
  pull_request:
    branches: [ main ]

env:
  XMAKE_PKG_CACHEDIR: ${{ github.workspace }}\.xmake-cache
  XMAKE_PKG_INSTALLDIR: ${{ github.workspace }}\.xmake-packages

jobs:
  xmake:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        mode:
          - releasedbg
        toolchain:
          - msvc
          - clang-cl

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"

      - name: Cache Xmake downloads
      uses: actions/cache@v5
      with:
          path: ${{ github.workspace }}\.xmake-cache
          key: ${{ runner.os }}-${{ runner.arch }}-xmake-downloads
          restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-xmake-

      - name: Cache Xmake packages
      uses: actions/cache@v5
      with:
          path: ${{ github.workspace }}\.xmake-packages
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.toolchain }}-xmake-pkgs-vulkan2-${{ hashFiles('xmake.lua', 'xmake-packages/**/*.lua') }}

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          $ver = "1.4.313.2"

          curl.exe -f -L `
            "https://sdk.lunarg.com/sdk/download/$ver/windows/vulkan-sdk.exe" `
            -o "$env:RUNNER_TEMP\VulkanSDK.exe"

          & "$env:RUNNER_TEMP\VulkanSDK.exe" `
            --accept-licenses `
            --default-answer `
            --confirm-command install

          $sdk = "C:\VulkanSDK\$ver"

          Add-Content $env:GITHUB_ENV "VULKAN_SDK=$sdk"
          Add-Content $env:GITHUB_PATH "$sdk\Bin"
          Add-Content $env:GITHUB_ENV "INCLUDE=$sdk\Include;$env:INCLUDE"

          if (!(Test-Path "$sdk\Include\vulkan\vulkan.h")) {
            throw "Vulkan headers were not installed."
          }

      - name: config
        run: xmake config -y --mode=${{ matrix.mode }} --toolchain=${{ matrix.toolchain }}

      - name: build
        run: xmake build -y -vD

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: f4ffmpeg-${{ matrix.toolchain }}
          path: |
            build/**/*.dll
            build/**/*.pdb
          if-no-files-found: error
